littlerobinson_query_builder:
    database:
        title: null
        is_dev_mode: false
        config_path: database-config.yml
        file_name: querybuilderdb
        params:
            driver: pdo_mysql
            host: 127.0.0.1
            port: 3306
            user: null
            password: null
            dbname: null
            charset: utf8mb4
    user: null
    association: null
    rules: null
    security:
        database: null