services:
    littlerobinson.doctrine_database:
        class: Littlerobinson\QueryBuilderBundle\Utils\DoctrineDatabase
        autowire: true
    littlerobinson.query_builder_doctrine:
        class: Littlerobinson\QueryBuilderBundle\Utils\QueryBuilderDoctrine
        autowire: true
    littlerobinson.query_backup:
        class: Littlerobinson\QueryBuilderBundle\Utils\QueryBackup
        autowire: true

